### ISSUE TITLE
Failure using BulkInsert but other calls work fine.

### ISSUE THREAD

**Issue by rkreiseloakwood** [ffhighwind/DapperExtraCRUD#10]
Trying to use version 1.5.2 in a .Net 6 project. (Converting to this project because Z.Dapper.Plus is a proprietary product.)

I have a method to call a stored procedure and one to update a single row in a single table. Both work flawlessly.
I have a method that does a bulk insert using BulkInsertAsync. It fails and throws a "parameter cannot be null" exception on the "connection" parameter.

I cloned the project so I could step into the DapperExtraCRUD code. When it gets here
public static async Task BulkInsertAsync<T>(this IDbConnection connection, IEnumerable<T> objs, IDbTransaction transaction = null, int commandTimeout = 30)
The connection parameter IS NOT null. That method calls 
public override void BulkInsert<T>(IDbConnection connection, IEnumerable<T> objs, IDbTransaction transaction, string tableName,
			DataReaderFactory factory, IEnumerable<SqlColumn> columns, int commandTimeout = 30, SqlBulkCopyOptions options = SqlBulkCopyOptions.Default). The connection there is not null. But when it hits 
using (SqlBulkCopy bulkCopy = new SqlBulkCopy(connection as SqlConnection, options, transaction as SqlTransaction)) it throws the error.

**Further investigation revealed that the "connection as SqlConnection" is actually returning null.** (line 86 of SqlServerAdapter)

**Comment by ffhighwind** [comment]
I might need more code to figure out what's going on. Not sure why this project is getting popularity recently, but this is the second person to post an issue in the last month.

First off, Bulk Insert only works for Microsoft SQL Server. If you are changing the SqlDialect to another DBMS like MySQL let me know. If you are using Microsoft Server then I will do some testing and make some updates.

**Comment by ffhighwind** [comment]
Can you give me a few lines of code where you're using Bulk Insert? Include the instantiation of the SqlConnection object as well.

**Comment by rkreiseloakwood** [comment]
Sorry, I have already removed this nuget package from my project and found another one which does not have this issue. So my code that called your package is gone. Please note the highlighted last sentence of the original message where I provided the file name and line number which exposes the problem. Note also that I am using .net 6. It might be that an IDBConnection can no longer be cast as a SqlConnection.

**Comment by rkreiseloakwood** [comment]
At my client's direction I switched back to this project. I got around the problem above by doing this:
var rslt = (_context.Conn as SqlConnection).BulkInsert(records);
