### ISSUE TITLE
Bulk Insert waits for triggered stored procedure to complete

### ISSUE THREAD

**Issue by rkreiseloakwood** [ffhighwind/DapperExtraCRUD#11]
This might be desired in some cases but in mine, I need the Bulk Insert call to return as soon as it finishes the insert. (The triggered process should run in the background. I do not need to know if it worked or not.) Research on the web leads me to believe this might be an option. But I suspect it would be a fair amount of work.

https://learn.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.beginexecutenonquery?redirectedfrom=MSDN&view=dotnet-plat-ext-7.0#System_Data_SqlClient_SqlCommand_BeginExecuteNonQuery 

For the time being, I am going to disable the trigger and call the stored procedure to which it points, manually in a separate thread.

**Comment by ffhighwind** [comment]
Hello. Have you tried using the async versions of Bulk Insert?
https://github.com/ffhighwind/DapperExtraCRUD/blob/master/DapperExtraCRUD/DapperExtraExtensions.cs#L250
I suppose I could create another set of methods that return IAsyncResult. Is there a standard for naming conventions with this? Current thoughts are AsyncResult, IAsync, AsyncCallback, AsAsync, AsyncOp.

**Comment by ffhighwind** [comment]
Actually, your best bet is to just run the synchronous method on a separate thread. Try calling Task.Run(() => ...)

**Comment by rkreiseloakwood** [comment]
I fear I must apologize. Bulk Insert is not the problem after all. The code was making another call after the bulk insert to update a status table. It was a trigger on that table that was calling a stored procedure. And the update command was not returning until the procedure finished. In my case the procedure was failing. But my code does not need to care whether it succeeds or not. It just needs to know if the update worked. (Which it did, but success was masked by the failure of the procedure.) My problem was solved by removing the trigger and making a separate call to the procedure in a try catch. That is obviously NOT a solution for everybody.
