### ISSUE TITLE
"ID" columns are not recognized

### ISSUE THREAD

**Issue by ShadyHarbinger** [ffhighwind/DapperExtraCRUD#2]
SqlTypeInfo cannot recognize ID columns because it checks SqlColumn.ColumnName that is the quoted name (e.g. "[ID]").
Original column name should be stored in a property (SqlColumn.UnquotedColumnName?) and that property should be checked for "ID".

**Comment by ShadyHarbinger** [comment]
I fixed it and created a pull request. Sorry if I did something wrong on GitHub. It is the first time I used GitHub. :)

**Comment by ffhighwind** [comment]
Hi Shady. I will check it out. Thank you for the bug report!

**Comment by ffhighwind** [comment]
I believe this is fixed with the last commit. See Dto11, Dto12, and Dto13 in the ConsoleTests project. I will push it to the nuget package within the next few days.

**Comment by ShadyHarbinger** [comment]
I tested it and it works. Tnx!
