### ISSUE TITLE
New extension methods to support autogeneration where condition

### ISSUE THREAD

**Issue by ShadyHarbinger** [ffhighwind/DapperExtraCRUD#4]
Could You please add new methods supporting where condition autogeneration

**Comment by ShadyHarbinger** [comment]
Could You please add few methods similar to `IEnumerable<T> GetList<T>(string whereCondition, object param, IDbTransaction transaction, bool buffered , int commandTimeout)` but without the whereCondition argument.

`IEnumerable<T> GetList<T>(object param, IDbTransaction transaction, bool buffered , int commandTimeout)`

For example the param would be `new { Count = 5, Date = new DateTime(2020, 10, 13) }`.
This case the method returns record where Count is 5 and Date is 10.13.2020.

Maybe there is a way to do that but I have not noticed it.

**Comment by ffhighwind** [comment]
You are right, this is not directly supported at the moment. That's mostly because I didn't do exhaustive testing on the WhereCondition generator, nor did I find myself using it. I could probably add this as an expression paramater, but I wanted some sort of caching mechanism for the most recent N calls so it isn't slow for loops. There's also some other issues that I could fix while I'm at it, like giving good error messages when you're passing in the wrong type.

**Comment by ShadyHarbinger** [comment]
If you plan to add this feature then I am going to implement it on my fork and use it till your version is done.
ExtraCRUD is the most comprehensive extension that I have found so I hope it will officially be added soon. :)

**Comment by ffhighwind** [comment]
I'll work on it. I'm debating developing something like Entity as a replacement to ExtraCRUD since I'd rather not rely on Dapper and my cache framework requires a lot of boilerplate code. If I do go that route that it's going to be a while, though.

**Comment by ffhighwind** [comment]
Also, the way you described isn't how it would be done.

Extension:
`IEnumerable<T> GetList<T>(Expression<Func<T, bool>> IDbTransaction transaction, bool buffered , int commandTimeout)`

Usage:
`List<T> list = GetList<T>((x) => x.Count = 5 && x.Date = new DateTime(2020, 10, 13));`

**Comment by ffhighwind** [comment]
This is mostly done. I still need to add the functionality to the AutoAccessObject, DataAccessObject, and cache framework. I'll try and do that tomorrow then push the nuget.

**Comment by ShadyHarbinger** [comment]
You are very productive.
I would have another question however it is not related to this issue. Can I update particular columns? E.g. if an entity got 5 fields but I need to update only 2 of them despite the other ones are also changed.

**Comment by ffhighwind** [comment]
This functionality is implemented but it seems like I forgot to add it to the extensions. I'll make sure to add it. 

Definition
`bool Update(this IDbConnection connection, object obj, IDbTransaction transaction = null, int commandTimeout = 30)`
Usage
`conn.Update<Type>(new { Key = value, Column = Value2 });`
Note that <Type> is required here.
