### ISSUE TITLE
Failure Accessing Postgresql DB

### ISSUE THREAD

**Issue by cpsmuniz** [ffhighwind/DapperExtraCRUD#9]
Hi, man. How is it going?

I'm trying to implement the DapperExtraCRUD in my project. But I'm getting issues accessing the DB through the code below:
![image](https://user-images.githubusercontent.com/11547076/203410368-75b1fb81-290f-4280-bb61-7c99b74d5455.png)

![image](https://user-images.githubusercontent.com/11547076/203409796-d5439471-9c30-4635-b329-79de0806deb1.png)

At the "conn.GetList<Patient>()" its breaking and getting the following issue:
"42601: syntax error at or near "["

POSITION: 8
SELECT [id],[country]
FROM cms_patient" 

Seems that these "["s are making the query wrong for postgres, I mean, it should be without them. 

Would you have any way to have it without them or other solution for it?

Thank you very much, dude.

**Comment by ffhighwind** [comment]
Hi. You're lucky I read my emails today. I've only been checking it once a month.

Have you tried calling ExtraCrud.SetAdapter(SqlAdapter.PostgreSQL))? You should only need to do this at the start of the program. There's a small chance you might need to call ExtraCrud.Purge<Patient>() as well.

**Comment by ffhighwind** [comment]
Sorry, I accidentally closed the issue. Let me know if this helped.

**Comment by ffhighwind** [comment]
Thinking back on this. You can also try doing these things:

ExtraCrud.Dialect = SqlDialect.PostgreSQL; // sets the default dialect to PostgreSQL

or when you define the class you can also set the dialect
[Table(name = "TableName", dialect = SqlDialect.PostgreSQL)] // changes the dialect of a specific table
class SomeClass
